### ISSUE TITLE
CSS-16 - Seletores

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#16]
# Seletores no CSS

## Introdução
Os seletores no CSS são fundamentais para aplicar estilos aos elementos HTML. Eles determinam quais elementos serão estilizados e permitem personalizar cores, tamanhos, posicionamento e muito mais. O CSS oferece diferentes tipos de seletores, como seletores de elementos, classes, IDs, seletores agrupados e pseudo-classes.

Entender os seletores corretamente é essencial para escrever código CSS limpo e eficiente, evitando redundâncias e garantindo um bom desempenho na renderização da página.

### 1. Seletor de elemento
```css
/* Aplica a cor azul a todos os parágrafos */
p {
    color: blue;
}
```

### 2. Seletor de classe
```css
/* Aplica um fundo cinza aos elementos com a classe "destaque" */
.destaque {
    background-color: gray;
    color: white;
}
```
```html
<p class="destaque">Este é um parágrafo destacado.</p>
```

### 3. Seletor de ID
```css
/* Aplica um tamanho de fonte maior ao elemento com ID "titulo" */
#titulo {
    font-size: 24px;
    font-weight: bold;
}
```
```html
<h1 id="titulo">Título Importante</h1>
```

### 4. Seletor de grupo
```css
/* Aplica a mesma cor de fundo para múltiplos elementos */
h1, h2, h3 {
    background-color: lightgray;
}
```

### 5. Pseudo-classe
```css
/* Altera a cor de um link quando o mouse passa por cima */
a:hover {
    color: red;
    text-decoration: underline;
}
```

## Referências
1. [MDN Web Docs - Seletores CSS](https://developer.mozilla.org/pt-BR/docs/Web/CSS/CSS_Selectors)
2. [W3Schools - CSS Selectors](https://www.w3schools.com/css/css_selectors.asp)

## Atividades
- [ ] Criar um arquivo `seletores.css` e testar os diferentes seletores básicos.
- [ ] Criar um arquivo HTML aplicando seletores de classe e ID para estilização específica.
- [ ] Utilizar uma pseudo-classe (`:hover`, `:focus`, etc.) para alterar um elemento dinamicamente.
