### ISSUE TITLE
CSS-17 - Cores e Fundos

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#17]
# Cores e Fundos no CSS

## Introdução
O CSS permite personalizar as cores dos elementos HTML e definir fundos para melhorar o design da página. Podemos usar valores de cores em diferentes formatos, como nomes de cores, códigos hexadecimais, valores RGB e HSL. Além disso, o CSS possibilita a aplicação de imagens de fundo, gradientes e transparência, oferecendo diversas opções para estilizar elementos visuais.

Compreender as propriedades de cores e fundos é essencial para criar interfaces atraentes e acessíveis.

### 1. Definindo cores usando diferentes formatos
```css
/* Cor pelo nome */
h1 {
    color: red;
}

/* Cor em hexadecimal */
p {
    color: #3498db;
}

/* Cor em RGB */
div {
    color: rgb(255, 165, 0);
}

/* Cor em HSL */
span {
    color: hsl(120, 100%, 50%);
}
```

### 2. Definindo cores de fundo
```css
/* Fundo sólido */
body {
    background-color: lightgray;
}

/* Fundo com imagem */
div {
    background-image: url('imagem.jpg');
    background-size: cover;
}
```

### 3. Criando gradientes como fundo
```css
/* Gradiente linear */
header {
    background: linear-gradient(to right, blue, purple);
}

/* Gradiente radial */
footer {
    background: radial-gradient(circle, red, yellow, green);
}
```

## Referências
1. [MDN Web Docs - Cores no CSS](https://developer.mozilla.org/pt-BR/docs/Web/CSS/color)
2. [W3Schools - Backgrounds no CSS](https://www.w3schools.com/css/css_background.asp)

## Atividades
- [ ] Criar um arquivo `cores.css` e testar diferentes formatos de cores.
- [ ] Criar um arquivo `fundos.css` e aplicar uma imagem de fundo a um elemento.
- [ ] Criar um cabeçalho com um gradiente de fundo usando `linear-gradient`.
