### ISSUE TITLE
CSS-18 - Tipografia

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#18]
# Tipografia no CSS

## Introdução
A tipografia no CSS permite definir estilos para textos, melhorando a legibilidade e a aparência da interface. Podemos controlar fontes, tamanhos, espaçamento entre caracteres e linhas, além de personalizar o alinhamento e o peso do texto.

O uso adequado das propriedades tipográficas é essencial para criar um design harmônico e agradável para o usuário.

### 1. Definição de fontes e tamanho do texto
```css
/* Fonte personalizada e tamanho */
body {
    font-family: Arial, sans-serif;
    font-size: 16px;
}
```

### 2. Alterando o peso e estilo da fonte
```css
h1 {
    font-weight: bold; /* Negrito */
    font-style: italic; /* Itálico */
}
```

### 3. Espaçamento entre caracteres e linhas
```css
p {
    letter-spacing: 2px; /* Espaçamento entre letras */
    line-height: 1.5; /* Espaçamento entre linhas */
}
```

### 4. Alinhamento do texto
```css
h2 {
    text-align: center; /* Centraliza o texto */
}
```

## Referências
1. [MDN Web Docs - Fontes e Tipografia](https://developer.mozilla.org/pt-BR/docs/Web/CSS/font)
2. [W3Schools - CSS Typography](https://www.w3schools.com/css/css_font.asp)

## Atividades
- [ ] Criar um arquivo `tipografia.css` e definir diferentes fontes para os textos.
- [ ] Aplicar espaçamentos personalizados entre letras e linhas em um parágrafo.
- [ ] Criar um cabeçalho alinhado ao centro com fonte negrito e itálico.
