### ISSUE TITLE
CSS-19 - Box Model

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#19]
# Box Model no CSS

## Introdução
O modelo de caixa (Box Model) no CSS define como os elementos são representados visualmente em uma página. Ele é composto por quatro áreas principais:
- **Content (Conteúdo):** A área onde o texto e outros elementos são exibidos.
- **Padding (Preenchimento):** Espaço entre o conteúdo e a borda do elemento.
- **Border (Borda):** Linha ao redor do elemento.
- **Margin (Margem):** Espaço externo entre o elemento e outros elementos.

Compreender o Box Model é essencial para controlar o layout e espaçamento dos elementos na página.

### 1. Estrutura do Box Model
```css
.box {
    width: 200px;
    height: 100px;
    padding: 10px;
    border: 5px solid black;
    margin: 20px;
    background-color: lightblue;
}
```
```html
<div class="box">Este é um exemplo do Box Model</div>
```

### 2. Alterando `box-sizing`
```css
/* box-sizing: border-box faz com que width e height incluam padding e border */
.box {
    width: 200px;
    height: 100px;
    padding: 10px;
    border: 5px solid black;
    box-sizing: border-box;
}
```

### 3. Ajustando margem automática para centralizar
```css
div {
    width: 300px;
    margin: 0 auto;
    background-color: lightgray;
    text-align: center;
}
```

## Referências
1. [MDN Web Docs - Box Model](https://developer.mozilla.org/pt-BR/docs/Web/CSS/box_model)
2. [W3Schools - Box Model](https://www.w3schools.com/css/css_boxmodel.asp)

## Atividades
- [ ] Criar um arquivo `box_model.css` e aplicar diferentes espaçamentos usando `margin`, `padding` e `border`.
- [ ] Criar um layout utilizando `box-sizing: border-box` para manter dimensões fixas.
- [ ] Centralizar uma `div` horizontalmente utilizando `margin: auto`.
