### ISSUE TITLE
CSS-20 - Display e Posicionamento

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#20]
# Display e Posicionamento no CSS

## Introdução
O CSS oferece diversas propriedades para controlar a exibição e o posicionamento dos elementos na página. As principais propriedades incluem:

- **`display`**: Define como um elemento é renderizado na tela.
- **`position`**: Controla a posição de um elemento dentro do layout.
- **`top, right, bottom, left`**: Especificam o deslocamento de um elemento posicionado.

Compreender essas propriedades é essencial para criar layouts organizados e responsivos.

### 1. Propriedade `display`
```css
/* Exibir elementos em linha */
.inline {
    display: inline;
    background-color: lightblue;
    padding: 5px;
}

/* Transformar um elemento em bloco */
.block {
    display: block;
    background-color: lightgreen;
    padding: 10px;
    width: 200px;
}
```
```html
<span class="inline">Texto Inline</span>
<div class="block">Texto em Bloco</div>
```

### 2. Propriedade `position`
```css
.relative {
    position: relative;
    left: 20px;
}

.absolute {
    position: absolute;
    top: 50px;
    right: 10px;
}

.fixed {
    position: fixed;
    bottom: 0;
    background-color: red;
    width: 100%;
    text-align: center;
    padding: 10px;
}
```
```html
<div class="relative">Elemento com posição relativa</div>
<div class="absolute">Elemento com posição absoluta</div>
<div class="fixed">Rodapé fixo</div>
```

### 3. Centralizando um elemento com `margin: auto`
```css
.centered {
    width: 200px;
    margin: 0 auto;
    background-color: yellow;
    text-align: center;
    padding: 10px;
}
```
```html
<div class="centered">Elemento Centralizado</div>
```

## Referências
1. [MDN Web Docs - Propriedade Display](https://developer.mozilla.org/pt-BR/docs/Web/CSS/display)
2. [MDN Web Docs - Propriedade Position](https://developer.mozilla.org/pt-BR/docs/Web/CSS/position)

## Atividades
- [ ] Criar um arquivo `display_positioning.css` e testar diferentes valores de `display`.
- [ ] Posicionar elementos utilizando `relative`, `absolute` e `fixed`.
- [ ] Centralizar uma `div` horizontalmente usando `margin: auto`.
