### ISSUE TITLE
CSS-21 - Flexbox

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#21]
# Flexbox no CSS

## Introdução
O **Flexbox** é um modelo de layout do CSS que facilita a criação de layouts flexíveis e responsivos. Ele permite distribuir os elementos dentro de um contêiner de forma eficiente, alinhando-os vertical e horizontalmente sem a necessidade de usar `float` ou `position absolute`.

O modelo flexível é controlado pela propriedade `display: flex;`, aplicada ao contêiner pai, enquanto os elementos filhos podem ser manipulados com diversas propriedades de alinhamento e distribuição.

### 1. Criando um contêiner flexível
```css
.container {
    display: flex;
    background-color: lightgray;
    padding: 10px;
}
.item {
    background-color: blue;
    color: white;
    margin: 5px;
    padding: 10px;
}
```
```html
<div class="container">
    <div class="item">Item 1</div>
    <div class="item">Item 2</div>
    <div class="item">Item 3</div>
</div>
```

### 2. Alinhamento de itens com `justify-content`
```css
.container {
    display: flex;
    justify-content: center; /* Centraliza os itens horizontalmente */
}
```

### 3. Alinhamento vertical com `align-items`
```css
.container {
    display: flex;
    height: 200px;
    align-items: center; /* Alinha os itens no centro verticalmente */
}
```

## Referências
1. [MDN Web Docs - Flexbox](https://developer.mozilla.org/pt-BR/docs/Web/CSS/CSS_Flexible_Box_Layout)
2. [W3Schools - CSS Flexbox](https://www.w3schools.com/css/css3_flexbox.asp)

## Atividades
- [ ] Criar um arquivo `flexbox.css` e implementar um layout básico usando `display: flex`.
- [ ] Usar `justify-content` para testar diferentes alinhamentos horizontais.
- [ ] Utilizar `align-items` para alinhar elementos verticalmente dentro do contêiner.
