### ISSUE TITLE
CSS-22 - Grid Layout

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#22]
# Grid Layout no CSS

## Introdução
O **CSS Grid Layout** é um sistema de layout bidimensional que permite organizar os elementos em linhas e colunas de forma eficiente. Ele é ideal para criar layouts complexos e responsivos sem precisar de hacks como `float` ou `flexbox` para alinhamento em múltiplas direções.

O Grid é definido usando a propriedade `display: grid;` no elemento contêiner e pode ser personalizado com `grid-template-columns`, `grid-template-rows`, `gap`, entre outras propriedades.

### 1. Criando um contêiner Grid básico
```css
.container {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr; /* Três colunas de largura igual */
    gap: 10px; /* Espaço entre os itens */
    background-color: lightgray;
    padding: 10px;
}
.item {
    background-color: blue;
    color: white;
    padding: 20px;
    text-align: center;
}
```
```html
<div class="container">
    <div class="item">1</div>
    <div class="item">2</div>
    <div class="item">3</div>
</div>
```

### 2. Definição de áreas no Grid com `grid-template-areas`
```css
.container {
    display: grid;
    grid-template-areas:
        "header header"
        "menu main"
        "footer footer";
    grid-template-columns: 1fr 2fr;
    grid-template-rows: auto;
}
.header {
    grid-area: header;
    background-color: red;
}
.menu {
    grid-area: menu;
    background-color: green;
}
.main {
    grid-area: main;
    background-color: blue;
}
.footer {
    grid-area: footer;
    background-color: gray;
}
```
```html
<div class="container">
    <div class="header">Cabeçalho</div>
    <div class="menu">Menu</div>
    <div class="main">Conteúdo</div>
    <div class="footer">Rodapé</div>
</div>
```

## Referências
1. [MDN Web Docs - CSS Grid](https://developer.mozilla.org/pt-BR/docs/Web/CSS/CSS_Grid_Layout)
2. [W3Schools - CSS Grid Layout](https://www.w3schools.com/css/css_grid.asp)

## Atividades
- [ ] Criar um arquivo `grid.css` e testar diferentes configurações de `grid-template-columns` e `grid-template-rows`.
- [ ] Criar um layout com três colunas utilizando Grid.
- [ ] Utilizar `grid-template-areas` para organizar um layout de cabeçalho, menu, conteúdo e rodapé.
