### ISSUE TITLE
CSS-23 - Animações e Transições

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#23]
# Animações e Transições no CSS

## Introdução
O CSS permite a criação de efeitos visuais dinâmicos através de **transições** e **animações**. As **transições** são usadas para alterar gradualmente as propriedades de um elemento, enquanto as **animações** permitem a criação de movimentos mais complexos com keyframes.

Esses efeitos melhoram a experiência do usuário e tornam a interface mais interativa sem a necessidade de JavaScript.

### 1. Criando uma transição suave com `transition`
```css
button {
    background-color: blue;
    color: white;
    padding: 10px 20px;
    border: none;
    transition: background-color 0.5s ease;
}

button:hover {
    background-color: red;
}
```
```html
<button>Passe o mouse</button>
```

### 2. Criando uma animação com `@keyframes`
```css
@keyframes mover {
    from {
        transform: translateX(0);
    }
    to {
        transform: translateX(100px);
    }
}

.div-animada {
    width: 100px;
    height: 100px;
    background-color: green;
    animation: mover 2s infinite alternate;
}
```
```html
<div class="div-animada"></div>
```

### 3. Animação de opacidade ao carregar a página
```css
@keyframes fadeIn {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}

.elemento {
    animation: fadeIn 1.5s ease-in-out;
}
```
```html
<div class="elemento">Texto que aparece suavemente</div>
```

## Referências
1. [MDN Web Docs - Transições CSS](https://developer.mozilla.org/pt-BR/docs/Web/CSS/CSS_Transitions)
2. [MDN Web Docs - Animações CSS](https://developer.mozilla.org/pt-BR/docs/Web/CSS/CSS_Animations)

## Atividades
- [ ] Criar um arquivo `animations.css` e implementar um botão com efeito de transição.
- [ ] Criar uma animação que mova um elemento horizontalmente utilizando `@keyframes`.
- [ ] Criar um efeito de fade-in para um elemento ao carregar a página.
