### ISSUE TITLE
CSS-24 - Pseudo-classes e Pseudo-elementos

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#24]
# Pseudo-classes e Pseudo-elementos no CSS

## Introdução
As **pseudo-classes** e **pseudo-elementos** são recursos do CSS que permitem aplicar estilos dinâmicos e avançados sem necessidade de adicionar classes ou modificar o HTML diretamente.

- **Pseudo-classes (`:`)**: Aplicam estilos a elementos com base em seu estado (exemplo: `:hover`, `:focus`, `:nth-child()`).
- **Pseudo-elementos (`::`)**: Permitem estilizar partes específicas de um elemento (exemplo: `::before`, `::after`).

Esses recursos são essenciais para criar interações dinâmicas e estilizações refinadas sem a necessidade de JavaScript.

### 1. Alterando a aparência de um link ao passar o mouse (`:hover`)
```css
a {
    color: blue;
    text-decoration: none;
}

a:hover {
    color: red;
    text-decoration: underline;
}
```
```html
<a href="#">Passe o mouse sobre mim</a>
```

### 2. Estilizando um campo de input quando recebe foco (`:focus`)
```css
input:focus {
    border: 2px solid green;
    outline: none;
}
```
```html
<input type="text" placeholder="Clique aqui para testar">
```

### 3. Selecionando elementos específicos com `nth-child()`
```css
li:nth-child(odd) {
    background-color: lightgray;
}
```
```html
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
    <li>Item 4</li>
</ul>
```

### 4. Criando elementos fictícios com `::before` e `::after`
```css
h1::before {
    content: "🔥 ";
}

h1::after {
    content: " 🚀";
}
```
```html
<h1>CSS Avançado</h1>
```

## Referências
1. [MDN Web Docs - Pseudo-classes](https://developer.mozilla.org/pt-BR/docs/Web/CSS/Pseudo-classes)
2. [MDN Web Docs - Pseudo-elementos](https://developer.mozilla.org/pt-BR/docs/Web/CSS/Pseudo-elements)

## Atividades
- [ ] Criar um arquivo `pseudo_classes.css` e aplicar `:hover` e `:focus` em diferentes elementos.
- [ ] Criar uma lista e estilizar os itens ímpares usando `nth-child(odd)`.
- [ ] Criar um título que utilize `::before` e `::after` para adicionar elementos decorativos.
