### ISSUE TITLE
CSS-26 - CSS Variables

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#26]
# CSS Variables (Custom Properties)

## Introdução
As **variáveis CSS** (também chamadas de **Custom Properties**) permitem armazenar valores reutilizáveis no CSS, tornando o código mais organizado, dinâmico e fácil de manter. Diferente das pré-processadores como SASS e LESS, as variáveis CSS são nativas do CSS e podem ser modificadas em tempo real usando JavaScript.

### **Vantagens do uso de variáveis CSS:**
- **Reutilização:** Evita a repetição de valores como cores, tamanhos e espaçamentos.
- **Facilidade de manutenção:** Alterar um valor central muda automaticamente todos os elementos que o utilizam.
- **Personalização dinâmica:** Pode ser alterada por JavaScript para criar temas personalizados.

### 1. Declarando variáveis no `:root`
O `:root` é um seletor especial que representa o elemento `<html>`, permitindo que as variáveis fiquem disponíveis globalmente.

```css
:root {
    --cor-primaria: #3498db;
    --cor-secundaria: #2ecc71;
    --fonte-principal: 'Arial', sans-serif;
    --tamanho-fonte: 16px;
}
```

### 2. Usando variáveis em propriedades CSS
Para utilizar uma variável, basta usar a função `var()`.

```css
body {
    background-color: var(--cor-primaria);
    color: white;
    font-family: var(--fonte-principal);
    font-size: var(--tamanho-fonte);
}

button {
    background-color: var(--cor-secundaria);
    color: white;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
}
```

## Exemplo Prático: Criando um Tema Claro e Escuro
Uma das aplicações mais comuns das variáveis CSS é a alternância entre **tema claro e escuro**.

```css
:root {
    --cor-fundo: #ffffff;
    --cor-texto: #000000;
}

[data-tema="escuro"] {
    --cor-fundo: #1e1e1e;
    --cor-texto: #ffffff;
}

body {
    background-color: var(--cor-fundo);
    color: var(--cor-texto);
    transition: background 0.3s, color 0.3s;
}
```
```html
<button onclick="alternarTema()">Alternar Tema</button>
<script>
    function alternarTema() {
        document.body.toggleAttribute('data-tema', 'escuro');
    }
</script>
```

## Definindo Variáveis Locais
As variáveis também podem ser definidas dentro de elementos específicos, tornando-as exclusivas para eles.

```css
.card {
    --card-bg: lightgray;
    --card-padding: 20px;
    background-color: var(--card-bg);
    padding: var(--card-padding);
    border-radius: 5px;
}
```

## Alterando Variáveis com JavaScript
Uma grande vantagem das variáveis CSS é que podemos modificá-las dinamicamente via JavaScript.

```html
<button onclick="mudarCor()">Mudar Cor</button>
<script>
    function mudarCor() {
        document.documentElement.style.setProperty('--cor-primaria', '#e74c3c');
    }
</script>
```

## Referências
1. [MDN Web Docs - CSS Variables](https://developer.mozilla.org/pt-BR/docs/Web/CSS/Using_CSS_custom_properties)
2. [W3Schools - CSS Custom Properties](https://www.w3schools.com/css/css3_variables.asp)

## Atividades
- [ ] Criar um arquivo `css_variables.css` e definir variáveis globais para cores e fontes.
- [ ] Criar um tema claro e escuro utilizando variáveis CSS.
- [ ] Utilizar JavaScript para alterar variáveis CSS dinamicamente.
