### ISSUE TITLE
CSS-27 - Grid Avançado

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#27]
# CSS Grid Avançado

## Introdução
O **CSS Grid Layout** é um sistema poderoso que permite criar layouts complexos com facilidade. Diferente do Flexbox, que trabalha em uma dimensão (linha ou coluna), o Grid é bidimensional, permitindo um controle preciso da disposição dos elementos na página.

Neste tópico, aprofundaremos o uso do Grid, abordando recursos avançados como **grid-template-areas**, **grid-auto-flow**, **minmax()**, **repeat()**, e **auto-fit/auto-fill**.

### 1. Definindo um Grid com `repeat()` e `minmax()`
Podemos definir colunas e linhas dinâmicas utilizando `repeat()` e `minmax()`, garantindo responsividade sem precisar declarar cada valor manualmente.

```css
.container {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    grid-template-rows: repeat(3, 100px);
    gap: 10px;
    background-color: lightgray;
    padding: 10px;
}
.item {
    background-color: blue;
    color: white;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 18px;
}
```

```html
<div class="container">
    <div class="item">1</div>
    <div class="item">2</div>
    <div class="item">3</div>
    <div class="item">4</div>
</div>
```

### 2. Usando `grid-template-areas`
Definir **áreas nomeadas** ajuda na organização visual e facilita o desenvolvimento.

```css
.container {
    display: grid;
    grid-template-areas:
        "header header"
        "sidebar content"
        "footer footer";
    grid-template-columns: 1fr 2fr;
    grid-template-rows: auto;
}

.header { grid-area: header; background-color: red; }
.sidebar { grid-area: sidebar; background-color: green; }
.content { grid-area: content; background-color: blue; }
.footer { grid-area: footer; background-color: gray; }
```

```html
<div class="container">
    <div class="header">Cabeçalho</div>
    <div class="sidebar">Menu</div>
    <div class="content">Conteúdo</div>
    <div class="footer">Rodapé</div>
</div>
```

### 3. `grid-auto-flow` para controle automático de posicionamento
A propriedade `grid-auto-flow` define como os elementos são distribuídos dentro do grid.

```css
.container {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-auto-flow: column; /* Organiza os elementos automaticamente em colunas */
    gap: 10px;
}
```

## Referências
1. [MDN Web Docs - CSS Grid](https://developer.mozilla.org/pt-BR/docs/Web/CSS/CSS_Grid_Layout)
2. [W3Schools - CSS Grid](https://www.w3schools.com/css/css_grid.asp)

## Atividades
- [ ] Criar um arquivo `grid_avancado.css` e testar `repeat()` e `minmax()` para tornar o layout responsivo.
- [ ] Criar um layout utilizando `grid-template-areas` para estruturar um site.
- [ ] Experimentar `grid-auto-flow` para organizar automaticamente os elementos do Grid.
