### ISSUE TITLE
CSS-28 - Flexbox Avançado

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#28]
# Flexbox Avançado no CSS

## Introdução
O **Flexbox** é um modelo de layout unidimensional que facilita o alinhamento e distribuição dos elementos em um contêiner. Ao dominar recursos avançados como `flex-grow`, `flex-shrink`, `flex-basis` e `align-self`, é possível criar layouts mais flexíveis e adaptáveis.

Neste tópico, exploraremos propriedades avançadas do Flexbox para otimizar o design e melhorar a responsividade de layouts web.

### 1. `flex-grow`: Controlando a expansão dos itens
A propriedade `flex-grow` define a capacidade de um item crescer dentro do contêiner.

```css
.container {
    display: flex;
    gap: 10px;
}
.item {
    flex-grow: 1; /* Todos os itens crescerão igualmente */
    background-color: blue;
    color: white;
    padding: 20px;
    text-align: center;
}
```

```html
<div class="container">
    <div class="item">Item 1</div>
    <div class="item">Item 2</div>
    <div class="item">Item 3</div>
</div>
```

### 2. `flex-shrink`: Controlando a redução dos itens
Define a capacidade de um item diminuir de tamanho caso o espaço seja reduzido.

```css
.item-1 { flex-shrink: 1; }
.item-2 { flex-shrink: 2; }
.item-3 { flex-shrink: 3; }
```

### 3. `flex-basis`: Definindo um tamanho inicial
Controla o tamanho base de um item antes que o `flex-grow` ou `flex-shrink` seja aplicado.

```css
.item {
    flex-basis: 200px; /* Define um tamanho inicial de 200px para cada item */
}
```

### 4. `align-self`: Alinhando itens individualmente
Permite alterar o alinhamento de um item específico dentro do contêiner Flexbox.

```css
.item-1 { align-self: flex-start; }
.item-2 { align-self: center; }
.item-3 { align-self: flex-end; }
```

## Referências
1. [MDN Web Docs - Flexbox](https://developer.mozilla.org/pt-BR/docs/Web/CSS/CSS_Flexible_Box_Layout)
2. [W3Schools - Flexbox](https://www.w3schools.com/css/css3_flexbox.asp)

## Atividades
- [ ] Criar um arquivo `flexbox_avancado.css` e testar `flex-grow` e `flex-shrink`.
- [ ] Criar um layout com `flex-basis` para definir tamanhos iniciais dos itens.
- [ ] Usar `align-self` para alinhar itens de forma independente dentro do Flexbox.
