### ISSUE TITLE
CSS-29 - Media Queries Avançadas

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#29]
# Media Queries Avançadas no CSS

## Introdução
As **Media Queries** permitem criar estilos responsivos adaptáveis a diferentes tamanhos de tela e dispositivos. No nível avançado, é possível utilizá-las para detectar preferências do usuário, características do dispositivo e até mesmo otimizar o carregamento de estilos para melhorar a performance.

### 1. Adaptação para diferentes larguras de tela
```css
@media (max-width: 768px) {
    body {
        background-color: lightblue;
    }
}
```
> **Explicação**: Quando a tela for menor que 768px, a cor de fundo mudará para azul-claro.

### 2. Detectando o modo escuro do usuário
```css
@media (prefers-color-scheme: dark) {
    body {
        background-color: #121212;
        color: white;
    }
}
```
> **Explicação**: Se o usuário estiver usando o modo escuro no sistema operacional, o site aplicará automaticamente um esquema de cores escuras.

### 3. Detectando a preferência de movimento reduzido
```css
@media (prefers-reduced-motion: reduce) {
    * {
        animation: none !important;
        transition: none !important;
    }
}
```
> **Explicação**: Se o usuário preferir menos animações, todas as animações e transições serão desativadas.

### 4. Estilização específica para telas de alta resolução
```css
@media (min-resolution: 2dppx) {
    .logo {
        background-image: url('logo-retina.png');
    }
}
```
> **Explicação**: Este código detecta telas com alta densidade de pixels (como Retina Displays) e carrega uma imagem otimizada para essa resolução.

### 5. Adaptação para orientação da tela
```css
@media (orientation: portrait) {
    body {
        font-size: 18px;
    }
}
```
> **Explicação**: O tamanho da fonte será maior quando o dispositivo estiver em modo retrato.

### 6. Aplicação condicional de estilos
```css
@media (max-width: 1024px) and (min-width: 600px) {
    .container {
        display: flex;
    }
}
```
> **Explicação**: O layout `flex` será aplicado somente entre 600px e 1024px de largura de tela.

## Referências
1. [MDN Web Docs - Media Queries](https://developer.mozilla.org/pt-BR/docs/Web/CSS/Media_Queries/Using_media_queries)
2. [W3Schools - CSS Media Queries](https://www.w3schools.com/css/css3_mediaqueries.asp)

## Atividades
- [ ] Criar um arquivo `media_queries.css` e aplicar um layout diferente para telas pequenas e grandes.
- [ ] Implementar um esquema de cores claro e escuro usando `prefers-color-scheme`.
- [ ] Aplicar `prefers-reduced-motion` para desativar animações para usuários que preferem menos movimento.
