### ISSUE TITLE
CSS-30 - Dark Mode

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#30]
# Dark Mode no CSS

## Introdução
O **Dark Mode** (Modo Escuro) é uma funcionalidade que permite aos usuários alternar entre um tema claro e escuro, melhorando a experiência visual e reduzindo o cansaço ocular. No CSS, podemos implementar o modo escuro utilizando **Media Queries (`prefers-color-scheme`)**, **variáveis CSS** e até mesmo **JavaScript** para personalização dinâmica.

### 1. Usando `prefers-color-scheme` para detectar o tema do sistema
```css
/* Tema Claro (Padrão) */
:root {
    --bg-color: white;
    --text-color: black;
}

/* Modo Escuro Detectado */
@media (prefers-color-scheme: dark) {
    :root {
        --bg-color: #121212;
        --text-color: white;
    }
}

body {
    background-color: var(--bg-color);
    color: var(--text-color);
    transition: background 0.3s, color 0.3s;
}
```
> **Explicação:** Esse método adapta automaticamente o site ao modo escuro configurado no sistema operacional do usuário.

### 2. Criando um botão para alternar entre Light/Dark Mode com CSS e JavaScript
```css
:root {
    --bg-color: white;
    --text-color: black;
}

[data-theme="dark"] {
    --bg-color: #121212;
    --text-color: white;
}

body {
    background-color: var(--bg-color);
    color: var(--text-color);
    transition: background 0.3s, color 0.3s;
}
```
```html
<button onclick="toggleDarkMode()">Alternar Tema</button>
<script>
function toggleDarkMode() {
    const body = document.body;
    const isDark = body.getAttribute("data-theme") === "dark";
    body.setAttribute("data-theme", isDark ? "light" : "dark");
}
</script>
```
> **Explicação:** Esse código adiciona um botão que permite ao usuário alternar entre os modos claro e escuro manualmente.

### 3. Armazenando a preferência do usuário com `localStorage`
```html
<button onclick="toggleDarkMode()">Alternar Tema</button>
<script>
function toggleDarkMode() {
    const body = document.body;
    const isDark = body.getAttribute("data-theme") === "dark";
    const newTheme = isDark ? "light" : "dark";
    body.setAttribute("data-theme", newTheme);
    localStorage.setItem("theme", newTheme);
}

// Aplicar o tema salvo ao carregar a página
const savedTheme = localStorage.getItem("theme") || "light";
document.body.setAttribute("data-theme", savedTheme);
</script>
```
> **Explicação:** Esse método mantém a escolha do usuário mesmo após atualizar a página, usando `localStorage`.

## Referências
1. [MDN Web Docs - prefers-color-scheme](https://developer.mozilla.org/pt-BR/docs/Web/CSS/@media/prefers-color-scheme)
2. [CSS Tricks - Dark Mode](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/)

## Atividades
- [ ] Criar um arquivo `dark_mode.css` e implementar a detecção automática do tema do sistema.
- [ ] Criar um botão que permita alternar entre temas claro e escuro.
- [ ] Implementar `localStorage` para salvar a escolha do usuário ao recarregar a página.
