### ISSUE TITLE
CSS-31 - SASS/SCSS

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#31]
# SASS/SCSS – Uso de Pré-processadores CSS

## Introdução
O **SASS (Syntactically Awesome Stylesheets)** é um pré-processador CSS que adiciona funcionalidades avançadas, como variáveis, aninhamento, mixins, funções e herança, tornando o código mais eficiente e modular. O **SCSS** é uma variação do SASS que mantém a sintaxe semelhante ao CSS tradicional.

O uso de pré-processadores melhora a organização do código e facilita a manutenção de projetos grandes.

## Instalação do SASS
Antes de utilizar o SASS/SCSS, é necessário instalá-lo. Caso tenha o Node.js instalado, execute o seguinte comando:

```sh
npm install -g sass
```

Para compilar um arquivo `.scss` em `.css`, utilize:

```sh
sass input.scss output.css
```

### 1. Uso de Variáveis
```scss
$cor-primaria: #3498db;
$fonte-principal: Arial, sans-serif;

body {
    background-color: $cor-primaria;
    font-family: $fonte-principal;
}
```
> **Explicação:** Permite armazenar valores reutilizáveis para evitar repetições e facilitar a manutenção.

### 2. Aninhamento de Seletores
```scss
nav {
    background: #333;
    ul {
        list-style: none;
        li {
            display: inline;
            a {
                color: white;
                text-decoration: none;
            }
        }
    }
}
```
> **Explicação:** O código acima gera seletores CSS aninhados, reduzindo a repetição de classes.

### 3. Mixins para Reutilização de Código
```scss
@mixin botao($cor) {
    background: $cor;
    color: white;
    padding: 10px 20px;
    border: none;
}

.botao-primario {
    @include botao(#3498db);
}

.botao-secundario {
    @include botao(#2ecc71);
}
```
> **Explicação:** Mixins permitem reutilizar conjuntos de estilos com parâmetros dinâmicos.

### 4. Herança com `@extend`
```scss
.mensagem {
    border: 1px solid gray;
    padding: 10px;
}

.mensagem-sucesso {
    @extend .mensagem;
    background: lightgreen;
}

.mensagem-erro {
    @extend .mensagem;
    background: lightcoral;
}
```
> **Explicação:** `@extend` evita duplicação de código ao reutilizar propriedades de outro seletor.

### 5. Funções para Manipulação de Cores
```scss
@function escurecer($cor, $quantidade) {
    @return darken($cor, $quantidade);
}

.botao {
    background: escurecer(#3498db, 10%);
}
```
> **Explicação:** Funções personalizadas permitem manipular valores diretamente no CSS.

## Referências
1. [SASS Official Documentation](https://sass-lang.com/documentation)
2. [MDN Web Docs - SASS](https://developer.mozilla.org/pt-BR/docs/Web/CSS/Sass)

## Atividades
- [ ] Criar um arquivo `styles.scss` e compilar para CSS.
- [ ] Utilizar variáveis e mixins para otimizar o código.
- [ ] Criar um sistema de cores dinâmico utilizando funções SASS.
