### ISSUE TITLE
CSS-32 - Design Responsivo Profundo

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#32]
# Design Responsivo Profundo no CSS

## Introdução
O **design responsivo** garante que uma página web seja visualmente adaptável a diferentes tamanhos de tela e dispositivos. Ele utiliza técnicas como **media queries**, **unidades flexíveis**, **layout fluído**, **grid e flexbox responsivos**, além de novos recursos como `clamp()`, `aspect-ratio` e `object-fit`.

A implementação de um design responsivo melhora a experiência do usuário, tornando o site acessível em desktops, tablets e smartphones sem necessidade de diferentes versões do código.

### 1. Usando `clamp()` para tamanhos de fonte flexíveis
```css
h1 {
    font-size: clamp(1.5rem, 5vw, 3rem);
}
```
> **Explicação:** O `clamp()` define um tamanho mínimo, ideal e máximo para a fonte baseado no tamanho da viewport.

### 2. Mantendo a proporção de elementos com `aspect-ratio`
```css
.video-container {
    aspect-ratio: 16 / 9;
    width: 100%;
}
```
> **Explicação:** `aspect-ratio` garante que um elemento mantenha a proporção desejada, como vídeos e imagens.

### 3. Ajustando imagens com `object-fit`
```css
img {
    width: 100%;
    height: 200px;
    object-fit: cover;
}
```
> **Explicação:** `object-fit: cover;` mantém o enquadramento correto da imagem dentro de seu contêiner.

### 4. Criando um layout responsivo com Grid
```css
.container {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 10px;
}
```
> **Explicação:** `auto-fit` e `minmax()` tornam o layout adaptável sem necessidade de media queries.

### 5. Criando um menu responsivo com Flexbox e Media Queries
```css
.menu {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}

@media (max-width: 768px) {
    .menu {
        flex-direction: column;
    }
}
```
> **Explicação:** O menu ajusta sua direção conforme a largura da tela, tornando-se vertical em telas menores.

## Referências
1. [MDN Web Docs - Design Responsivo](https://developer.mozilla.org/pt-BR/docs/Learn/CSS/CSS_layout/Responsive_Design)
2. [W3Schools - Responsive Web Design](https://www.w3schools.com/css/css_rwd_intro.asp)

## Atividades
- [ ] Criar um arquivo `responsivo.css` e testar o uso de `clamp()` para fontes responsivas.
- [ ] Implementar `aspect-ratio` para garantir proporções corretas em elementos multimídia.
- [ ] Criar um layout responsivo utilizando Grid e Flexbox sem media queries.
