### ISSUE TITLE
CSS-33 - Avançado para Performance

### ISSUE THREAD

**Issue by devairdarolt** [devairdarolt/front-end-aline#33]
# CSS Avançado para Performance

## Introdução
O desempenho do CSS impacta diretamente a velocidade de carregamento e a experiência do usuário em um site. Técnicas avançadas de otimização evitam **reflows** e **repaints**, reduzem o uso de seletores pesados e minimizam a sobrecarga de processamento do navegador.

A implementação correta dessas técnicas melhora o **tempo de renderização** e proporciona um site mais eficiente e responsivo.

### 1. Evitar seletores CSS ineficientes
```css
/* Evite seletores complexos como este */
div > p span + a {
    color: red;
}

/* Prefira seletores mais diretos */
.botao {
    color: red;
}
```
> **Explicação:** Seletores complexos forçam o navegador a percorrer a árvore DOM várias vezes, reduzindo a performance.

### 2. Utilizar `will-change` para animações mais suaves
```css
.botao {
    will-change: transform, opacity;
    transition: transform 0.3s ease, opacity 0.3s ease;
}
```
> **Explicação:** `will-change` informa ao navegador quais propriedades serão animadas, permitindo otimização prévia.

### 3. Evitar o uso excessivo de `@import`
```css
/* Evite múltiplos @import */
@import url("reset.css");
@import url("theme.css");
```
> **Explicação:** O uso de `@import` bloqueia o carregamento da página. Prefira consolidar os estilos em um único arquivo CSS.

### 4. Minificar e comprimir arquivos CSS
```sh
# Minificando um arquivo CSS com Node.js
npm install -g clean-css-cli
cleancss -o estilo.min.css estilo.css
```
> **Explicação:** Arquivos minificados reduzem o tamanho do CSS, melhorando o tempo de carregamento.

### 5. Utilizar `CSS Containment` para isolar estilos
```css
.section {
    contain: layout paint;
}
```
> **Explicação:** `contain` informa ao navegador que o elemento não afeta outros elementos, reduzindo o custo de renderização.

## Referências
1. [MDN Web Docs - CSS Performance](https://developer.mozilla.org/en-US/docs/Web/CSS/Performance)
2. [Google Developers - Optimize CSS Delivery](https://web.dev/optimize-css/)

## Atividades
- [ ] Criar um arquivo `performance.css` e testar seletores otimizados.
- [ ] Implementar `will-change` em elementos animados.
- [ ] Minificar um arquivo CSS e comparar o tamanho do arquivo original com o minificado.
